### ISSUE TITLE
Rebasing RFC-10 branch

### ISSUE THREAD

**Issue by piogor** [tango-controls/rfc#100]
As part of merging current WIP into develop branch, I am rebasing the raw-rfc-10-request-reply, so it is even with current  ‘draft’ and ‘develop’. 
There is also an issue due to renaming 10/README.md to 10/RequestReply.md (at least my git requires manual intervention for merging), which will be solved by this rebase. You may see how the history will look like by inspecting ‘develop’ branch.

@hardion, @lorenzopivetta , @bourtemb, I will force-push it, if it is ok with you. (It will rewrite a history, so you will need to update your forks).

**Comment by lorenzopivetta** [comment]
@piogor , @mliszcz fine with me.

**Comment by piogor** [comment]
Thanks @lorenzopivetta and @bourtemb. The branch commits history is now much cleaner.
