### ISSUE TITLE
Licensing this documentation

### ISSUE THREAD

**Issue by srgblnch** [tango-controls/rfc#31]
In the template preamble there is a copyright information that license this project as GPLv3+. But this is a documentation repository project so, perhaps a documentation license could be more convenient.

Following the FSF licenses, one first think in the [GFDL](https://www.gnu.org/licenses/fdl-1.3.html). By the way, in the popular imagination, we have more Creative Commons in mind.

Wikipedia's page for the [GDFL](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) mentions that the wikipedia itself uses this license coupled with the [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/). Perhaps we could use this option or left it as CC BY-SA.

To mention also. 
* The zmq-rfc are licensed as GPLv3+. 
* The [python peps](https://github.com/python/peps) requires to sign a contributor agreement and select which license will you use in your contribution [AFLv2.1](https://spdx.org/licenses/AFL-2.1.html) or [Apache License v2.0](https://opensource.org/licenses/apache2.0.php).
* The IETF RFCs comes with a close license.

**Comment by hardion** [comment]
GPL is used for the zmq rfc. The idea behind is to protect the specification against the lockage of a third party.
The all history of COSS is explain in the article written by Peter Hintjens about Open Specification System: https://www.ifosslr.org/index.php/ifosslr/article/view/32/69 ,especially the paragraph "GPL for Free and Open Standards"

One comment though, the licence of the specification does not affect or constraint the license of the implementations.
