### ISSUE TITLE
RFCs split/refactor

### ISSUE THREAD

**Issue by piogor** [tango-controls/rfc#34]
There are (or will be) parts of existing RFCs which are worth to be made separate. The candidates are:
- parts which are duplicated (like datatypes) in many RFC-s
- specification which may change with its own lifecycle, having no or litle impact on the other items

After the first cycle of writing (RFC-1 - RFC-5), a review will be made to identify the candidates.

**Comment by piogor** [comment]
Currently, proposed candidates are:
- by @piogor types as common part
- by @andygotz: Attribute Configuration Properties, Attribute Event Properties and Attribute Standard Properties

**Comment by piogor** [comment]
Next candidate for its RFC:
* Pipe

**Comment by gwen-soleil** [comment]
what do you about adding a RFC describing DevFailed? This new RFC should be then referenced to all RFCs that deal with error management. E.g. for RFC-5, a DevFailed must be thrown when  a communication error occurs with the Tango database.

**Comment by hardion** [comment]
> Next candidate for its RFC:
> 
> * Pipe

RFC 7? There is a empty space

**Comment by hardion** [comment]
> what do you about adding a RFC describing DevFailed? This new RFC should be then referenced to all RFCs that deal with error management. E.g. for RFC-5, a DevFailed must be thrown when a communication error occurs with the Tango database.

Yes. Maybe we should have this RFC proposed by @piogor  about Tango Type which will include the DevFailed.

**Comment by hardion** [comment]
Can we replace RFC 9 "Class Model" by "Type"?
The Class can be defined in the RFC Device around the Object concept.

**Comment by piogor** [comment]
API_ErrorReasons (or Const) RFC, see #61, https://github.com/tango-controls/rfc/pull/61#discussion_r370675337
