### ISSUE TITLE
The Command specification

### ISSUE THREAD

**Issue by hardion** [tango-controls/rfc#5]
# Goals
Specify the concept of Tango Command

# Use Cases
There are several use cases:
* A command "Stop" can trigger the ending of a movement for a motor or an integration for a detector
* A command "Send" can take any SCPI command as argument and wait for the reply

# Specification
The specification has to be written and can be validated when all possible combination of command/argument/output can be specified.

**Comment by piogor** [comment]
It seems to be done. I am closing the issue :-).
