### ISSUE TITLE
Some thoughts on RFC-10&11

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rfc#64]
RFC-10 should define and specify the following:

 * Handshake
      - use of virtual addressing      
      - use of peer-to-peer connection
      - use of authentication and authorization 
      - use of encrypted p2p connection

* Runtime behavior
      - connection establishment for each req-rep OR
      - connection reusage for multiple interactions i.e. multiple devices on a single network entry point etc
      - messages multiplexing/demultiplexing
      - what to do with stalled connection
      - cache control
      - authentication and authorization
      - encryption

* What info protocol passes over the wire
      - to read/write an attribute
      - to execute command
      - to read/write pipe
      - to read/write properties 
      - etc

 * Fault tolerance
      - transparent connection reestablishing   
      - in case Tango DB is down
      - in case upstream server is down/restarts
      - in case client is down/restarts

In RFC-11 it is important to highlight what parts of the protocol are inherited from CORBA and what are implemented in Server/Client API libraries

**Comment by hardion** [comment]
Thanks for starting thinking of RFC-10.
What you wrote is really good start. I like the idea of saying which spec are implemented by the underline protocol and which one has to be implemented.

What about to start a PR with a skeleton from this idea? Do you think we can distribute the work easily by using a raw branch in tango-rfc and pr there?

**Comment by Ingvord** [comment]
Using branch in this repo will allow everyone contribute directly in that branch

**Comment by mliszcz** [comment]
Hi all,
Just a question: what will be the added value (from Tango v10 PoV) of having CORBA-specific details/features specified in Tango 9 RFC? Looks like a wasted effort to me.

**Comment by Ingvord** [comment]
Good question :)

Do we consider virtual addressing i.e. when client connects to `tango://host:port/domain/family/member` and not for instance to `tcp://host:port` as a feature of Tango 9?

I think so. But it is partially inherited from CORBA via using IORs internally etc. 

So as I stated in the very first comment:

> RFC-10 should define and specify the following:

It means in RFC-10 we have to specify what features of Tango 9 we are currently using, sometimes taken for granted. While in RFC-11 we should specify what features are totally inherited from CORBA, what - partially and, finally, what are implemented purely in Server/Client API libraries

With this we will have a clear vision what parts of CORBA and its protocol must be re-implemented in Tango 10 (or inherited from other fancy framework like gRPC)

Does that answer you question @mliszcz ?

**Comment by mliszcz** [comment]
Thanks Igor for a detailed explanation. While I see your point, I was just afraid that we may dive too deep into underlying transport and start documenting features not relevant to Tango itself: connection establishment, encryption, etc.

**Comment by piogor** [comment]
There is a dedicated branch fo rfc-10 PRs: https://github.com/tango-controls/rfc/tree/raw-rfc-10-request-reply

**Comment by hardion** [comment]
This issue has been fulfilled. Thanks Piotr.
I will create a PR from this branch to Draft to be able to make reference of the RFC10 development.
